import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { fetchWeatherData, getWeatherForecast } from "../axios/weatherData";
import { BiCurrentLocation } from "react-icons/bi";

import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [location, setLocation] = useState("London");
  const [isSubmit, setIsSubmit] = useState(false);
  const [data, setData] = useState();
  const [fiveDayForecast, setFiveDayForecast] = useState();

  function handleChange(e: React.ChangeEvent<HTMLInputElement>) {
    const { name, value } = e.target;
    return setLocation(value);
  }

  function handleSubmit(e: React.MouseEvent<HTMLElement>) {
    // track when submit button clicked
    e.preventDefault();
    setIsSubmit((prev) => !prev);
  }

  useEffect(() => {
    // run everytime submit is clicked
    fetchWeatherData(location, setData);
    getWeatherForecast(location, setFiveDayForecast);
  }, [isSubmit]);

  // console.log(fiveDayForecast);

  function getLocation() {
    // retrieve geolocation
    navigator.geolocation.getCurrentPosition(function (position) {
      console.log("Latitude is :", position.coords.latitude);
      console.log("Longitude is :", position.coords.longitude);
    });
  }

  return (
    <>
      <Head>
        <title>Weather app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/public/Icon.png" />
      </Head>

      <main>
        <form>
          <input
            style={{
              background: "transparent",
            }}
            type="text"
            name="place"
            placeholder="eg: London"
            value={location}
            onChange={handleChange}
          ></input>
          <button onClick={handleSubmit}>Submit</button>
        </form>
        <button onClick={getLocation}>
          <BiCurrentLocation />
        </button>
      </main>
    </>
  );
}
