import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import {
  fetchWeatherData,
  getWeatherForecast,
  fetchWeatherDataLongLat,
  fetchWeatherForecastLongLat,
} from "../axios/weatherData";
import { BiCurrentLocation } from "react-icons/bi";
import { useEffect, useState } from "react";
import LeftSideInformation from "../components/leftSide";
import RightSideInformation from "../components/rightSide";

export default function Home() {
  const [location, setLocation] = useState("paris"); // set location
  const [isSubmit, setIsSubmit] = useState(false); // track submit button
  const [data, setData] = useState(""); // hold apu data for current weather
  const [fiveDayForecast, setFiveDayForecast] = useState(""); // hold data for five day forecast

  function handleChange(e: React.ChangeEvent<HTMLInputElement>) {
    const { name, value } = e.target;
    return setLocation(value);
  }

  function handleSubmit(e: React.MouseEvent<HTMLElement>) {
    // track when submit button clicked
    e.preventDefault();
    setIsSubmit((prev) => !prev);
  }

  useEffect(() => {
    // run everytime submit is clicked
    fetchWeatherData(location, setData);
    getWeatherForecast(location, setFiveDayForecast);
  }, [isSubmit]);

  // console.log(fiveDayForecast);
  // console.log(isGeoLocation);

  function getLocation() {
    // retrieve geolocation
    // navigator.geolocation.getCurrentPosition(function (position) {
    //   fetchWeatherDataLongLat(
    //     position.coords.longitude.toString(),
    //     position.coords.latitude.toString(),
    //     setData
    //   );
    // });
    //-----------testing
    // setIfGeolocation((prev: any) => {
    //   return !prev;
    // });
    navigator.geolocation.getCurrentPosition(function (position) {
      fetchWeatherDataLongLat(
        position.coords.longitude.toString(),
        position.coords.latitude.toString(),

        setData
      );
      fetchWeatherForecastLongLat(
        position.coords.longitude.toString(),
        position.coords.latitude.toString(),
        setFiveDayForecast
      );
    });
  }

  // useEffect(() => {
  //   navigator.geolocation.getCurrentPosition(function (position) {
  //     fetchWeatherDataLongLat(
  //       position.coords.longitude.toString(),
  //       position.coords.latitude.toString(),
  //       setData
  //     );
  //     fetchWeatherForecastLongLat(
  //       position.coords.longitude.toString(),
  //       position.coords.latitude.toString(),
  //       setFiveDayForecast
  //     );
  //   });
  // }, [ifGeolocation]);
  //-----------
  console.log(data);

  return (
    <>
      <Head>
        <title>Weather app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/public/Icon.png" /> */}
      </Head>

      <main>
        <form>
          <input
            style={{
              background: "transparent",
            }}
            type="text"
            name="place"
            placeholder="eg: London"
            value={location}
            onChange={handleChange}
          ></input>
          <button onClick={handleSubmit}>Submit</button>
        </form>
        <button onClick={getLocation}>
          <BiCurrentLocation />
        </button>

        <div>
          {data && fiveDayForecast && (
            <div>
              <LeftSideInformation data={data} />
              <RightSideInformation data={data} forecast={fiveDayForecast} />
            </div>
          )}
        </div>
      </main>
    </>
  );
}
